### PR TITLE
added vimrc keybind imitation file

### PR DESCRIPTION
**Pull request by tommy-mor**
Adds #6 as discussed. There may be some edge cases, but every bind in the readme seems to work correctly.
Also fixes a type in readme I think, correct me if it was right before!

### CODE REVIEW

**Comment by tommy-mor** [comment]
All the changed keybinds work in visual mode, just checked.

**Comment by wbolster** [comment]
cool, thanks for checking!

**Comment by wbolster** [comment]
@tommy-mor i just made a tiny tweak to your example.vimrc; you may be interested:

154b34f52e4fbe71c212dba1646409f33522c014

**Comment by tommy-mor** [comment]
Thank you! Today I learn about ```U``` command in vim. Surprised I did not see that duplicate...

**Pull request merged**
